
const delimiter = "## Introduction"
const header = """

<!-- This file is generated by `.github/workflows/create_readme.yml` and should not be edited directly. -->

<div align="center">

<p><img height="200px" src="docs/source/assets/logo.svg"/></p>

# Speculator.jl

[![Documentation Stable](https://img.shields.io/badge/Documentation-stable-blue.svg)](https://jakobjpeters.github.io/Speculator.jl/)
[![Documentation Development](https://img.shields.io/badge/Documentation-development-blue.svg)](https://jakobjpeters.github.io/Speculator.jl/development/)

[![Continuous Integration Workflow](https://github.com/jakobjpeters/Speculator.jl/workflows/Continuous%20Integration/badge.svg)](https://github.com/jakobjpeters/Speculator.jl/actions/workflows/continuous_integration.yml)
[![Documentation Workflow](https://github.com/jakobjpeters/Speculator.jl/workflows/Documentation/badge.svg)](https://github.com/jakobjpeters/Speculator.jl/actions/workflows/documentation.yml)

[![Codecov](https://codecov.io/gh/jakobjpeters/Speculator.jl/graph/badge.svg?token=KNLZXD2MV0)](https://codecov.io/gh/jakobjpeters/Speculator.jl)
[![Downloads](https://img.shields.io/badge/dynamic/json?url=http%3A%2F%2Fjuliapkgstats.com%2Fapi%2Fv1%2Fmonthly_downloads%2FSpeculator&query=total_requests&suffix=%2Fmonth&label=Downloads)](https://juliapkgstats.com/pkg/Speculator)
[![Dependents](https://juliahub.com/docs/General/Speculator/stable/deps.svg)](https://juliahub.com/ui/Packages/General/Speculator?t=2)

</div>

"""

open("README.md"; write = true) do file
    print(
        file, header, delimiter, last(split(read("docs/source/index.md", String), delimiter))
    )
end
