
name: Documentation
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    branches:
      - main
    tags: '*'
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - name: Install dependencies
        run: julia --color=yes --project=docs --eval 'using Pkg; Pkg.develop(PackageSpec(; path = ".")); Pkg.instantiate()'
      - name: Build and deploy
        run: julia --color=yes --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
